### ISSUE TITLE
opening the pages

### ISSUE THREAD

**Issue by iam-ganzy** [MedRecChain/penultimate-modification#15]
i have a problem opening the pages. can you please help?
what about login?

**Comment by 0xGhada** [comment]
@iam-ganzy of course, be sure that you change the admin address in the smart contract to become an admin then you can make migrate and treat withe web   ...  I will solve it soon 
![image](https://github.com/MedRecChain/MedRecChain/assets/115355629/fb50b1fe-d55d-4ad6-9669-0605679edddd)

**Comment by iam-ganzy** [comment]
Okay, i will try it. Thank you

**Comment by 0xGhada** [comment]
@iam-ganzy  You are welcome :) , if not working ... i will make video to how to Run this project from scratch
